### ISSUE TITLE
DNS is not applicable from CONFIG (DNS addresses are hard-coded)

### ISSUE THREAD

**Issue by chayeon** [joyent/sdc-hermes#1]
Hello,

I'm collecting Triton usage logs into our private Manta object storage which is not registered in the Google DNS (8.8.8.8, 8.8.4.4).

As you know, each Triton node sends its usage logs to Manta via hermes proxy. Then hermes proxy resolves Manta FQDN using DNSes which <b>SHOULD BE</b> written in the configuration file. 

FYI. DNS nameservers are validated in proxy.js as follows:

<pre>
function
validate_config(cfg)
{
	...
	if (<b>!Array.isArray(cfg.nameservers)</b>) {
		LOG.info('configuration invalid/missing "nameservers"');
		<b>return (false);</b>
	}
	...
}
</pre>

But, the hermes proxy ignored the `cfg.namesevers` configuration item in runtime.
I debugged and found that proxy.js uses DNS nameservers addresses hard-codded as follows.

<pre>
function
main()
{
	CONFIG = read_config();
	...
	PS = new lib_proxy_server.ProxyServer({
		log: LOG,
		bind_port: CONFIG.bind_port,
		bind_ip: CONFIG.bind_ip,
		backend_host: CONFIG.backend_host,
		backend_port: CONFIG.backend_port,
		<b>nameservers: [
			{ address: '8.8.8.8', port: 53, type: 'udp' },
			{ address: '8.8.4.4', port: 53, type: 'udp' }
		]</b>
	});
}
</pre>

I think the nameservers information should be read in CONFIG as follows:
<pre>
		nameservers: CONFIG.nameservers
</pre>

Thank you.

**Comment by chayeon** [comment]
Hi,
I have made a pull request. Please check it out.

**Comment by jclulow** [comment]
I have filed [TOOLS-1622](https://smartos.org/bugview/TOOLS-1622) for this issue.

**Comment by jclulow** [comment]
In the end, I had to fix another issue resulting from Manta services that have a large number of load balancer IPs ([TOOLS-1641](https://smartos.org/bugview/TOOLS-1641)).  The fix for that issue should remove this problem as well, making our use of DNS resolvers aligned with the rest of the `sdc` zone.
